steps:
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: coverage/$(packageName)/cobertura-coverage.xml
    reportDirectory: coverage/$(packageName)
    failIfCoverageEmpty: true
  condition: succeededOrFailed()
  displayName: Publish code coverage results
