steps:
- task: PublishTestResults@2
  inputs:
    testRunTitle: $(packageName)
    searchFolder: $(System.DefaultWorkingDirectory)/junit/$(packageName)
    testResultsFormat: JUnit
    testResultsFiles: "**/TESTS*.xml"
  condition: succeededOrFailed()
  displayName: Publish test results
